/* Ihsan's solution */

/* Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:


1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...


By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms. */



// Write a function fibSeq. This function will return all the Fibonacci numbers that are less than 4000000.

// To start, we will initialize two variables.







function sumFibonacci() {

var sum = 0;

var fibArray = fibSeq();



for( var i = 0, n = fibArray.length; i<n; i++) {

sum += fibArray[i];

}


return sum;

}



function fibSeq() {


var a = 1;

var b = 2;

var next = a + b; 


var fibArray = []



while(next < 4000000) {

if(next % 2 === 0) {

fibArray.push(next);

}



a = b

b = next

next = a+b

}



return fibArray;


}


console.log(fibSeq());

console.log(sumFibonacci());